stages:          # List of stages for jobs, and their order of execution
  - test

# unit-test-job:   # This job runs in the test stage.
#   stage: test    # It only starts when the job in the build stage completes successfully.
#   script:
#     - echo "Running unit tests... This will take about 60 seconds."
#     - sleep 10
#     - echo "Code coverage is 90%"

lint-test-job:
 image: node:latest
 stage: lint
 script:
  - npm ci
  - npm run lint
